start_pi_exes should now work in parallel

diff --git a/start_pi_exes b/start_pi_exes
--- a/start_pi_exes
+++ b/start_pi_exes
@@ -1,6 +1,16 @@
 #!/bin/bash
 # starts the executables on the raspberry pis
 
+
+check_process_up () {
+    PID="$(ssh $1 "pgrep $2")"
+    if [ -z "$PID" ]
+    then
+        echo "Aborting - the process on $1 was not started"
+        exit 1
+    fi
+}
+
 source etc/config
 
 
@@ -8,37 +18,33 @@ source etc/config
 ./stop_pi_exes
 
 
+# startup exes
 # sync boards
 for SYNC_PI_ALIAS in "${SYNC_PI_ALIASES[@]}"
 do
-    echo "starting exe on $SYNC_PI_ALIAS:"
-
-    # start pi executables
-    ssh $SYNC_PI_ALIAS "cd $PI_SYNCDIR; ./run_sync"
-
-    # make sure they are up
-    PID=$(ssh $SYNC_PI_ALIAS "pgrep $SYNC_EXE")
-    if [ -z "$PID" ]
-    then
-        echo "Aborting - the process on $SYNC_PI_ALIAS was not started"
-        exit 1
-    fi
+    echo "starting exe on $SYNC_PI_ALIAS"
+    ssh $SYNC_PI_ALIAS "cd $PI_SYNCDIR; ./run_sync" &
 done
-
 
 # rdout boards
 for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
 do
-    echo "starting exe on $RDOUT_PI_ALIAS:"
-
-    # start pi executables
-    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; ./run_rdout"
-
-    # make sure they are up
-    PID=$(ssh $RDOUT_PI_ALIAS "pgrep $RDOUT_EXE")
-    if [ -z "$PID" ]
-    then
-        echo "Aborting - the process on $RDOUT_PI_ALIAS was not started"
-        exit 1
-    fi
+    echo "starting exe on $RDOUT_PI_ALIAS"
+    ssh $RDOUT_PI_ALIAS "cd $PI_RDOUTDIR; ./run_rdout" &
 done
+wait
+
+
+# check if the processes are up
+# sync boards
+for SYNC_PI_ALIAS in "${SYNC_PI_ALIASES[@]}"
+do
+    check_process_up "$SYNC_PI_ALIAS" "$SYNC_EXE" &
+done
+
+# rdout boards
+for RDOUT_PI_ALIAS in "${RDOUT_PI_ALIASES[@]}"
+do
+    check_process_up "$RDOUT_PI_ALIAS" "$RDOUT_EXE" &
+done
+wait
