updated pwr_cycle to use GNU parallel and output to pwr.log on each pi

diff --git a/etc/pwr_cycle b/etc/pwr_cycle
--- a/etc/pwr_cycle
+++ b/etc/pwr_cycle
@@ -4,11 +4,4 @@ source etc/config
 
 ./stop_pi_exes
 
-# power cycle
-for rdout_pi_alias in "${rdout_pi_aliases[@]}"
-do
-    echo "power cycling $rdout_pi_alias"
-    # ssh $rdout_pi_alias "cd $pi_rdoutdir; sudo ./bin/pwr_cycle_v1" &
-    ssh $rdout_pi_alias "cd $pi_rdoutdir; sudo ./bin/pwr_cycle_v2" &
-done
-wait
+parallel $parallel_rdout_args "cd $pi_rdoutdir; sudo ./bin/pwr_cycle_v2 > pwr.log || echo -e '\033[0;91mpower cycle failed - check pwr.log\033[0m'"
