Added log files and error checking for fpga programming and IP/MAC scripts

diff --git a/rdout/prog_rdout b/rdout/prog_rdout
--- a/rdout/prog_rdout
+++ b/rdout/prog_rdout
@@ -1,9 +1,28 @@
 #!/bin/bash
 
+check_retval () {
+    if [ $1 -ne 0 ]
+    then
+        echo "Programming failed. Check prog.log"
+        exit 1
+    fi
+}
+
+# compile
 ./compile-obj
 
-sudo ./bin/program_fpga 0 < fw/data_orm_dly.hex
-sudo ./bin/program_fpga 1 < fw/data_orm_dly.hex
-sudo ./bin/program_fpga 2 < fw/data_orm_dly.hex
-sudo ./bin/program_fpga 3 < fw/data_orm_dly.hex
-sudo ./bin/program_fpga 4 < fw/ctl_orm_dly.hex
+# clear log file
+echo "" > prog.log
+
+# DATA ORMs
+for ORM_IDX in {0..3}
+do
+    echo "Programming DATA ORM$ORM_IDX"
+    sudo ./bin/program_fpga $ORM_IDX < fw/data_orm_dly.hex >> prog.log 2>&1
+    check_retval "$?"
+done
+
+# CTL ORM
+echo "Programming CTL ORM"
+sudo ./bin/program_fpga 4 < fw/ctl_orm_dly.hex >> prog.log 2>&1
+check_retval "$?"
diff --git a/setup_ipbus b/setup_ipbus
--- a/setup_ipbus
+++ b/setup_ipbus
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# function to check return values
+check_retval () {
+    if [ $1 -ne 0 ]
+    then
+        exit 1
+    fi
+}
+
 # general variables
 RDOUT_ALIAS="rdout"
 SYNC_ALIAS="sync"
@@ -15,7 +23,10 @@ rsync -az --delete rdout/ $RDOUT_ALIAS:$PI_RDOUTDIR
 
 # install firmware
 ssh $RDOUT_ALIAS "cd $PI_RDOUTDIR; ./prog_rdout"
+check_retval "$?"
 ssh $SYNC_ALIAS "cd $PI_SYNCDIR; ./prog_sync"
+check_retval "$?"
 
 # set ip/mac addresses
 ssh $RDOUT_ALIAS "cd $PI_RDOUTDIR; ./set_ip"
+check_retval "$?"
