rdout/set_ipbus_ip now prints an error message and stops when the IP was incorrectly set

diff --git a/rdout/set_ipbus_ip b/rdout/set_ipbus_ip
--- a/rdout/set_ipbus_ip
+++ b/rdout/set_ipbus_ip
@@ -14,3 +14,8 @@ fi
 # set ip address
 echo "Setting IPBus IP/MAC"
 sudo ./bin/set_ipbus_ip $BOARDNUM > ip.log 2>&1
+if [ $? -ne 0 ]
+then
+    echo "IPBus IP setting failed. Check ip.log"
+    exit 1
+fi
